# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
symbol = "î¬© "
disabled = true

[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = 'î­ '
[aws.region_aliases]
us-east-1 = 'va'
eu-central-1 = 'fr'

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'
truncate_to_repo = true

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 12
truncation_symbol = ''
ignore_branches = ['master', 'main']

[memory_usage]
disabled = true
threshold = -1
symbol = ' '
style = 'bold dimmed green'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = true

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = true

[shell]
zsh_indicator = 'îš‘ '
style = 'cyan bold'
disabled = true

[golang]
symbol = "î˜§"
format = ' [ó°Ÿ“ $version](bold cyan) '
version_format = 'v${major}.${minor}'

[lua]
symbol = "î ¦ "
format = ' [ó°¢± $version](bold blue) '

[nodejs]
symbol = "îµ„ "
format = ' [ó°™ $version](bold green) '
version_format = 'v${major}'

[python]
symbol = 'î˜† '
pyenv_version_name = false
pyenv_prefix = ''
version_format = 'v${major}.${minor}'

[rust]
symbol = 'î¨ '
format = ' [ó±˜— $version](red bold)'

[c]
symbol = "î˜ "
format = ' [$name $version]($style)'
